# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Curso-Taller de Python para Análisis Estadístico en Ciencias de la Salud"
author: Christian Alejandro Delaflor Wagner
logo: logo.png

copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  allow_errors: true  # Permite errores en las celdas de código, útil para mostrar ejemplos de errores comunes

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/chrisdewa/curso_python  # Online location of your book
  path_to_book: docs_raw  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)
  provider: github  # The provider of the repository, e.g., 'github', 'gitlab', etc.

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository

launch_buttons:
  colab_url: https://colab.research.google.com
  notebook_interface: classic  # or jupyterlab if you prefer
  thebe: false  # set to true if you want in-page code execution too

html:
  favicon: logo.ico
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  #theme: sphinx_book_theme
  extra_footer: |
    <p> 
      Todos los derechos reservados.
      <img src="https://hitscounter.dev/api/hit?url=https%3A%2F%2Fchrisdewa.github.io%2Fcurso_python&label=Vistas&icon=eye&color=%239ec5fe&message=&style=for-the-badge&tz=Mexico%2FGeneral">
    <p> 
sphinx:
  config:
    language: es
  extra_extensions:
    - sphinxcontrib.mermaid