title: "Curso-Taller de Python para Análisis Estadístico en Ciencias de la Salud"
remote_theme: just-the-docs/just-the-docs

search_enabled: true
heading_anchors: true

includes_head: _includes/head_custom.html

callouts:
  important:
    title: Important
    color: purple
  info:
    title: Info
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: red

mermaid:
  version: "11.6.0"

toc: true
toc_levels: 1..3
toc_label: Contenido
description: "Curso de Python desde cero, para aprender programación estadística enfocada a ciencias de la salud."

aux_links:
  "GitHub Repo":
    - "https://github.com/chrisdewa/curso_python"
  "Libretas":
    - "https://github.com/chrisdewa/curso_python/tree/main/libretas"
