title: "Curso de Python"
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Optional: adds the outline on the right
aux_links:
  "GitHub Repo":
    - "https://github.com/chrisdewa/curso_python"
